import { sha256 } from 'hash-wasm';
import type { NetworkTrustBoundary } from './contracts';
import type { AdaptiveNode, AdaptiveNodePersistence } from './nodes';
import type { AuthenticatedDeviceContext } from '../devices/lifecycle';
import { assertIssuedDeviceContext } from '../devices/authenticatedContext';

export type BridgeService = { protocol: 'tcp' | 'udp'; port: number };
export type SiteRoute = { version: 1; routeId: string; sourceNetworkId: string; destinationNetworkId: string; sourceBridgeDeviceId: string; destinationBridgeDeviceId: string; sourceCidr: string; destinationCidr: string; services: readonly BridgeService[]; issuerDeviceId: string; issuerIdentityReference: string; sourceEpoch: number; sourceCommitment: string; destinationEpoch: number; destinationCommitment: string; expiresAt: number; digest: string };
export interface BridgeNetworkStateProvider { state(networkId: string): Promise<{ epoch: number; commitment: string; isOwner(deviceId: string, identityReference: string): boolean } | undefined>; }
export interface SiteRoutePersistence { read(routeId: string): Promise<SiteRoute | undefined>; compareAndSwap(routeId: string, expected: SiteRoute | undefined, next: SiteRoute): Promise<boolean>; claim(key: string, expiresAt: number): Promise<boolean>; }
export interface EncryptedBridgeTransport { send(route: SiteRoute, payload: unknown): Promise<void>; onPacket(listener: (routeId: string, payload: unknown) => Promise<void>): () => void; }
export interface PlatformBridgeAdapter { readonly platform: 'linux-tun' | 'windows-wintun' | 'macos-network-extension' | 'android-vpn-service'; install(route: SiteRoute): Promise<void>; remove(routeId: string): Promise<void>; }
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const octet = '(?:25[0-5]|2[0-4]\\d|1?\\d?\\d)';
const host = new RegExp(`^(?:10\\.${octet}\\.${octet}\\.${octet}|192\\.168\\.${octet}\\.${octet}|172\\.(?:1[6-9]|2\\d|3[01])\\.${octet}\\.${octet})/32$`);
const validServices = (value: readonly BridgeService[]): boolean => value.length > 0 && value.length <= 32 && value.every((item) => (item.protocol === 'tcp' || item.protocol === 'udp') && Number.isSafeInteger(item.port) && item.port > 0 && item.port <= 65535);
const digest = async (route: Omit<SiteRoute, 'digest'>): Promise<string> => sha256(JSON.stringify(route));
const bridgeNode = (node: AdaptiveNode | undefined): boolean => !!node && node.role === 'permanent' && node.capabilities.bridge && node.status === 'online';

/** Explicit host/service routes only. No route implies no LAN visibility. */
export class SiteToSiteBridgeRuntime {
  constructor(private readonly nodes: AdaptiveNodePersistence, private readonly networks: BridgeNetworkStateProvider, private readonly persistence: SiteRoutePersistence, private readonly trust: NetworkTrustBoundary, private readonly now: () => number = Date.now) {}
  async authorize(context: AuthenticatedDeviceContext, input: Omit<SiteRoute, 'version' | 'routeId' | 'issuerDeviceId' | 'issuerIdentityReference' | 'sourceEpoch' | 'sourceCommitment' | 'destinationEpoch' | 'destinationCommitment' | 'expiresAt' | 'digest' | 'issuerDeviceId' | 'issuerIdentityReference'> & { ttlMs?: number }): Promise<SiteRoute> {
    assertIssuedDeviceContext(context); const issuer = context.authenticatedSender; await this.trust.assertTrusted(); const source = await this.networks.state(input.sourceNetworkId); const destination = await this.networks.state(input.destinationNetworkId);
    if (!source || !destination || !source.isOwner(issuer.deviceId, issuer.identityReference) || !host.test(input.sourceCidr) || !host.test(input.destinationCidr) || !validServices(input.services) || input.sourceNetworkId === input.destinationNetworkId) throw new Error('Bridge route authorization rejected.');
    await this.assertBridges(input.sourceNetworkId, input.sourceBridgeDeviceId, input.destinationNetworkId, input.destinationBridgeDeviceId);
    const unsigned = { version: 1 as const, routeId: crypto.randomUUID(), sourceNetworkId: input.sourceNetworkId, destinationNetworkId: input.destinationNetworkId, sourceBridgeDeviceId: input.sourceBridgeDeviceId, destinationBridgeDeviceId: input.destinationBridgeDeviceId, sourceCidr: input.sourceCidr, destinationCidr: input.destinationCidr, services: input.services, issuerDeviceId: issuer.deviceId, issuerIdentityReference: issuer.identityReference, sourceEpoch: source.epoch, sourceCommitment: source.commitment, destinationEpoch: destination.epoch, destinationCommitment: destination.commitment, expiresAt: this.now() + (input.ttlMs ?? 5 * 60_000) };
    return { ...unsigned, digest: await digest(unsigned) };
  }
  async install(context: AuthenticatedDeviceContext, route: SiteRoute): Promise<void> { const { digest: claimed, ...unsigned } = route; assertIssuedDeviceContext(context, route); await this.trust.assertTrusted(); const source = await this.networks.state(route.sourceNetworkId); const destination = await this.networks.state(route.destinationNetworkId); if (context.authenticatedSender.deviceId !== route.issuerDeviceId || context.authenticatedSender.identityReference !== route.issuerIdentityReference || !uuid.test(route.routeId) || route.expiresAt <= this.now() || claimed !== await digest(unsigned) || !source || !destination || route.sourceNetworkId === route.destinationNetworkId || !source.isOwner(route.issuerDeviceId, route.issuerIdentityReference) || source.epoch !== route.sourceEpoch || source.commitment !== route.sourceCommitment || destination.epoch !== route.destinationEpoch || destination.commitment !== route.destinationCommitment || !host.test(route.sourceCidr) || !host.test(route.destinationCidr) || !validServices(route.services)) throw new Error('Bridge route rejected.'); await this.assertBridges(route.sourceNetworkId, route.sourceBridgeDeviceId, route.destinationNetworkId, route.destinationBridgeDeviceId); if (!await this.persistence.claim(route.routeId, route.expiresAt) || !await this.persistence.compareAndSwap(route.routeId, undefined, route)) throw new Error('Bridge route replayed.'); }
  async allows(routeId: string, sourceHost: string, destinationHost: string, service: BridgeService): Promise<boolean> { const route = await this.activeRoute(routeId); return !!route && route.sourceCidr === `${sourceHost}/32` && route.destinationCidr === `${destinationHost}/32` && route.services.some((entry) => entry.protocol === service.protocol && entry.port === service.port); }
  async attachEncryptedTransport(transport: EncryptedBridgeTransport, listener: (route: SiteRoute, payload: unknown) => Promise<void>): Promise<() => void> { await this.trust.assertTrusted(); return transport.onPacket(async (routeId, payload) => { const route = await this.activeRoute(routeId); if (!route) throw new Error('Bridge packet rejected.'); await listener(route, payload); }); }
  private async activeRoute(routeId: string): Promise<SiteRoute | undefined> { await this.trust.assertTrusted(); const route = await this.persistence.read(routeId); if (!route || route.expiresAt <= this.now()) return undefined; const { digest: claimed, ...unsigned } = route; const source = await this.networks.state(route.sourceNetworkId); const destination = await this.networks.state(route.destinationNetworkId); if (claimed !== await digest(unsigned) || !source || !destination || !source.isOwner(route.issuerDeviceId, route.issuerIdentityReference) || source.epoch !== route.sourceEpoch || source.commitment !== route.sourceCommitment || destination.epoch !== route.destinationEpoch || destination.commitment !== route.destinationCommitment) return undefined; try { await this.assertBridges(route.sourceNetworkId, route.sourceBridgeDeviceId, route.destinationNetworkId, route.destinationBridgeDeviceId); return route; } catch { return undefined; } }
  private async assertBridges(sourceNetwork: string, sourceDevice: string, destinationNetwork: string, destinationDevice: string): Promise<void> { const source = (await this.nodes.read(sourceNetwork)).find((node) => node.deviceId === sourceDevice); const destination = (await this.nodes.read(destinationNetwork)).find((node) => node.deviceId === destinationDevice); if (!bridgeNode(source) || !bridgeNode(destination)) throw new Error('Bridge node rejected.'); }
}
export class MemorySiteRoutePersistence implements SiteRoutePersistence { constructor(private readonly now: () => number = Date.now) {} private readonly routes = new Map<string, SiteRoute>(); private readonly claimed = new Set<string>(); async read(id: string): Promise<SiteRoute | undefined> { const route = this.routes.get(id); return route && structuredClone(route); } async compareAndSwap(id: string, expected: SiteRoute | undefined, next: SiteRoute): Promise<boolean> { if (JSON.stringify(this.routes.get(id)) !== JSON.stringify(expected)) return false; this.routes.set(id, structuredClone(next)); return true; } async claim(id: string, expiresAt: number): Promise<boolean> { if (expiresAt <= this.now() || this.claimed.has(id)) return false; this.claimed.add(id); return true; } }
