import { AdaptiveNodeRuntime, MemoryAdaptiveNodePersistence, chooseAdaptiveRoute } from './nodes';
import { DeviceContextAuthority } from '../devices/authenticatedContext';
const owner = '11111111-1111-4111-8111-111111111111'; const node = '22222222-2222-4222-8222-222222222222'; const network = '33333333-3333-4333-8333-333333333333';
const trust = (revoked = false) => ({ assertTrusted: async () => { if (revoked) throw new Error('revoked'); }, snapshot: async () => ({ list: { identityReference: 'account', epoch: 1, devices: [{ deviceId: owner, publicIdentityReference: 'owner', state: 'active' as const }, { deviceId: node, publicIdentityReference: 'node', state: revoked ? 'revoked' as const : 'active' as const }] }, commitment: 'commitment' }) });
const context = () => new DeviceContextAuthority({ ready: true, encrypted: true, initialize: async () => undefined, destroy: () => undefined, encrypt: async () => ({ version: 1, strategy: 'test', data: {} }), decrypt: async () => new ArrayBuffer(0) }, 'network', { deviceId: owner, identityReference: 'owner', userScope: 'account', verified: true }).localContext();
describe('adaptive nodes', () => {
  it('rejects fake/replayed capability authorization and revoked nodes', async () => { const store = new MemoryAdaptiveNodePersistence(); const runtime = new AdaptiveNodeRuntime(store, trust()); const auth = await runtime.authorize(context(), network, { deviceId: node, identityReference: 'node' }, 'register', 'active', { relay: true, bridge: false, storage: false }); await expect(runtime.apply(context(), { ...auth, digest: 'fake' })).rejects.toThrow('rejected'); await runtime.apply(context(), auth); await expect(runtime.apply(context(), auth)).rejects.toThrow('rejected'); await expect(new AdaptiveNodeRuntime(store, trust(true)).heartbeat(network, node, 'node')).rejects.toThrow('revoked'); });
  it('falls back from direct to active node and then server relay', async () => { const store = new MemoryAdaptiveNodePersistence(); const runtime = new AdaptiveNodeRuntime(store, trust()); const auth = await runtime.authorize(context(), network, { deviceId: node, identityReference: 'node' }, 'register', 'permanent', { relay: true, bridge: true, storage: false }); await runtime.apply(context(), auth); await runtime.heartbeat(network, node, 'node'); expect(chooseAdaptiveRoute(false, await runtime.available(network))).toBe('active-node'); expect(chooseAdaptiveRoute(true, [])).toBe('direct'); expect(chooseAdaptiveRoute(false, [])).toBe('server-relay'); });
});
