import type { PrivateNetworkPacket, PrivateNetworkRelay, PrivateNetworkSessionBinding } from './contracts';

const encoder = new TextEncoder(); const decoder = new TextDecoder();
const valid = (value: unknown): value is PrivateNetworkPacket => !!value && typeof value === 'object' && (value as PrivateNetworkPacket).version === 1 && typeof (value as PrivateNetworkPacket).networkId === 'string' && typeof (value as PrivateNetworkPacket).messageId === 'string' && typeof (value as PrivateNetworkPacket).sessionId === 'string' && Number.isSafeInteger((value as PrivateNetworkPacket).expiresAt);

/** Opaque packet adapter: established CryptoSession supplies authentication and encryption. */
export class AuthenticatedPrivateNetworkTransport {
  private listener?: (packet: PrivateNetworkPacket) => Promise<void>;
  private unsubscribe?: () => void;
  private readonly seen = new Map<string, number>();
  constructor(private readonly binding: PrivateNetworkSessionBinding, private readonly relay: PrivateNetworkRelay, private readonly assertPeer: () => Promise<void>, private readonly now: () => number = Date.now) {}
  async send(payload: unknown, ttlMs = 60_000): Promise<void> { await this.assertPeer(); if (!this.binding.cryptoSession.ready || !this.binding.cryptoSession.encrypted) throw new Error('Private network session unavailable.'); const packet: PrivateNetworkPacket = { version: 1, networkId: this.binding.networkId, senderDeviceId: this.binding.localDeviceId, senderIdentityReference: this.binding.localIdentityReference, receiverDeviceId: this.binding.peerDeviceId, sessionId: this.binding.sessionId, messageId: crypto.randomUUID(), expiresAt: this.now() + ttlMs, payload }; await this.relay.send(this.binding.peerDeviceId, await this.binding.cryptoSession.encrypt('signaling', encoder.encode(JSON.stringify(packet)).buffer as ArrayBuffer)); }
  onPacket(listener: (packet: PrivateNetworkPacket) => Promise<void>): () => void { this.listener = listener; this.unsubscribe = this.relay.onEnvelope((sender, envelope) => this.receive(sender, envelope)); return () => { this.listener = undefined; this.unsubscribe?.(); }; }
  private async receive(sender: string, envelope: import('../core/contracts').EncryptedEnvelope): Promise<void> { await this.assertPeer(); if (sender !== this.binding.peerDeviceId || !this.binding.cryptoSession.ready || !this.binding.cryptoSession.encrypted) throw new Error('Private network peer rejected.'); let packet: unknown; try { packet = JSON.parse(decoder.decode(await this.binding.cryptoSession.decrypt('signaling', envelope))); } catch { throw new Error('Private network packet rejected.'); } if (!valid(packet) || packet.networkId !== this.binding.networkId || packet.sessionId !== this.binding.sessionId || packet.senderDeviceId !== this.binding.peerDeviceId || packet.senderIdentityReference !== this.binding.peerIdentityReference || packet.receiverDeviceId !== this.binding.localDeviceId || packet.expiresAt <= this.now()) throw new Error('Private network packet rejected.'); for (const [key, expiry] of this.seen) if (expiry <= this.now()) this.seen.delete(key); const key = `${packet.sessionId}:${packet.messageId}`; if (this.seen.has(key)) throw new Error('Private network packet replayed.'); this.seen.set(key, packet.expiresAt); if (this.listener) await this.listener(packet); }
}

export const connectivityOrder = (lanAvailable: boolean, internetAvailable: boolean): readonly import('./contracts').ConnectivityMode[] => lanAvailable ? (internetAvailable ? ['lan', 'internet', 'relay'] : ['lan', 'relay']) : (internetAvailable ? ['internet', 'relay'] : ['relay']);
